//AUTOGENERATED FILE FROM png2asset
// Conversion args: Font.png -keep_palette_order -tiles_only -spr8x8 -sprite_no_optimize -keep_duplicate_tiles

#ifndef METASPRITE_Font_H
#define METASPRITE_Font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Font_TILE_ORIGIN 0
#define Font_TILE_W 8
#define Font_TILE_H 8
#define Font_WIDTH 208
#define Font_HEIGHT 16
#define Font_TILE_COUNT 52
#define Font_PALETTE_COUNT 4
#define Font_COLORS_PER_PALETTE 4
#define Font_TOTAL_COLORS 16

BANKREF_EXTERN(Font)

extern const palette_color_t Font_palettes[16];
extern const uint8_t Font_tiles[832];

#endif
